### ISSUE TITLE
Move to python3

### ISSUE THREAD

**Issue by MassimoLauria** [MassimoLauria/cnfgen#93]
We will drop compatibility of Python 2.7 and move directly to Python 3.6.

Given the small user base this should not be a huge problem.

**Comment by sahmed95** [comment]
Is this the reason why I am not able to install it in my current python3 environment with the error:

```
Collecting cnfgen
  Using cached https://files.pythonhosted.org/packages/69/77/cc550fb40563ea69341ae17f2a0021f584259b5e885c493fdff570f619e8/CNFgen-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ehuxn33u/cnfgen/setup.py", line 8, in <module>
        import cnfformula.prjdata as p
      File "/tmp/pip-install-ehuxn33u/cnfgen/cnfformula/__init__.py", line 3, in <module>
        from .cnf import CNF
      File "/tmp/pip-install-ehuxn33u/cnfgen/cnfformula/cnf.py", line 27, in <module>
        from .graphs import bipartite_sets,neighbors
      File "/tmp/pip-install-ehuxn33u/cnfgen/cnfformula/graphs.py", line 272
        except networkx.NetworkXError,errmsg:
                                     ^
    SyntaxError: invalid syntax
```

**Comment by alugowski** [comment]
I made a PR to fix this https://github.com/MassimoLauria/cnfgen/pull/96

If you want to use the library on Python3 right now you can install directly from GitHub:

    pip install git+https://github.com/alugowski/cnfgen.git@2to3#egg=cnfgen

**Comment by MassimoLauria** [comment]
Thank you @alugowski I merged your changes.
